kind: PersistentVolume
apiVersion: v1
metadata:
  name: apicuriodb-aws-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apicuriodata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
